/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTypeRouteImport } from './routes/test.$type'
import { Route as ResultTypeRouteImport } from './routes/result.$type'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTypeRoute = TestTypeRouteImport.update({
  id: '/test/$type',
  path: '/test/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultTypeRoute = ResultTypeRouteImport.update({
  id: '/result/$type',
  path: '/result/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/result/$type': typeof ResultTypeRoute
  '/test/$type': typeof TestTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/result/$type': typeof ResultTypeRoute
  '/test/$type': typeof TestTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/result/$type': typeof ResultTypeRoute
  '/test/$type': typeof TestTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/result/$type' | '/test/$type'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/result/$type' | '/test/$type'
  id: '__root__' | '/' | '/admin' | '/result/$type' | '/test/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ResultTypeRoute: typeof ResultTypeRoute
  TestTypeRoute: typeof TestTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$type': {
      id: '/test/$type'
      path: '/test/$type'
      fullPath: '/test/$type'
      preLoaderRoute: typeof TestTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$type': {
      id: '/result/$type'
      path: '/result/$type'
      fullPath: '/result/$type'
      preLoaderRoute: typeof ResultTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ResultTypeRoute: ResultTypeRoute,
  TestTypeRoute: TestTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
